version: '3.4'
services:
    
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.0.9-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

  jobs:
    depends_on:
      - db
      - redis
      - app
    build: .
    command: bash start_jobs
    volumes:
      - .:/secret_santa
    volumes_from:
      - box
  
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/secret_santa
    ports:
      - "3000:3000"
    depends_on:
      - db
      - 'redis'
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  db:
  box: