version: '3.4'
services:
    
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  jobs:
    depends_on:
      - db
      - redis
      - app
    build: .
    command: bash start_jobs
    volumes:
      - .:/secret_santa
    volumes_from:
      - box
    env_file:
      - .env
  
  app:
    build: .
    command: bash start
    env_file:
      - .env
    volumes:
      - .:/secret_santa
    ports:
      - "3000:3000"
    depends_on:
      - db
      - 'redis'
    volumes_from:
      - box

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  db:
  box: